name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          commit_user_name: Muhammad Rusdi
          commit_user_email: mhmrofficial@gmail.com